version: '3'

services:

  redis-master1:
    container_name: redis-master1
    build: dockernode
    ports: 
      - "7000:6379"
    networks:
         extnetwork:
            ipv4_address: 172.19.0.2

  redis-slave1:
    container_name: redis-slave1
    build: dockernode
    command: redis-server --slaveof redis-master1 6379
    links:
      - redis-master1
    ports: 
      - "7001:6379"
    networks:
         extnetwork:
            ipv4_address: 172.19.0.3

  redis-master2:
    container_name: redis-master2
    build: dockernode
    ports: 
      - "7002:6379"
    networks:
         extnetwork:
            ipv4_address: 172.19.0.4

  redis-slave2:
    container_name: redis-slave2
    build: dockernode
    command: redis-server --slaveof redis-master2 6379
    links:
      - redis-master2
    ports: 
      - "7003:6379"
    networks:
         extnetwork:
            ipv4_address: 172.19.0.5

  redis-master3:
    container_name: redis-master3
    build: dockernode
    ports: 
      - "7004:6379"
    networks:
         extnetwork:
            ipv4_address: 172.19.0.6

  redis-slave3:
    container_name: redis-slave3
    build: dockernode
    command: redis-server --slaveof redis-master3 6379
    links:
      - redis-master3
    ports: 
      - "7005:6379"
    networks:
         extnetwork:
            ipv4_address: 172.19.0.7

  redis-cluster-creator:
    container_name: redis-cluster-creator
    build: createnode
    networks:
         extnetwork:
    links:
      - redis-master1
      - redis-master2
      - redis-master3
      - redis-slave1
      - redis-slave2
      - redis-slave3
    
  redis-sentinel-1:
    container_name: redis-sentinel-1
    build: sentinel
    networks:
         extnetwork:
    links:
      - redis-master1
      - redis-master2
      - redis-master3

  redis-sentinel-2:
    container_name: redis-sentinel-2
    build: sentinel
    networks:
         extnetwork:
    links:
      - redis-master1
      - redis-master2
      - redis-master3

  redis-sentinel-3:
    container_name: redis-sentinel-3
    build: sentinel
    networks:
         extnetwork:
    links:
      - redis-master1
      - redis-master2
      - redis-master3

networks:
   extnetwork:
      ipam:
         config:
         - subnet: 172.19.0.0/16